### ISSUE TITLE
Project Lacks a License

### ISSUE THREAD

**Issue by beelze-b** [Computational-Morphogenomics-Group/MarkerMap#18]
Might be worth bringing up to Soledad and Bianca. I assume the package is meant to be used by other researchers, so thinking about a license they can use is important.

**Comment by WilsonGregory** [comment]
Oh great point. Do you have any experience with open source licenses? I feel like I usually see GNU GPL or the MIT License on projects.

**Comment by WilsonGregory** [comment]
Oh I forgot to post an update here. I talked with Soledad about licenses on Friday, it sounded like she had used the MIT license before and recommended that one. I am planning on putting together a PR to add the license as well as the init.py or config.py files or whatever is needed to make it so that you can do a pip editable install as a package for it locally. The goal would be eventually add it to pip so you don't need to download the github repo first of course.

**Comment by WilsonGregory** [comment]
Added the MIT license.
